### ISSUE TITLE
Kodi starts before mysql

### ISSUE THREAD

**Issue by mknuepfer** [solbero/guide-kodi-lutris#2]
Hi,

i want to use a mysql backend for Kodi. Mysql is installed locally on the HTPC and the advancedsettings.xml is configured properly. But if Kodi starts on boot it can not connect to mysql.

If i quit Kodi and restart it from the desktop everything works well and Kodi can connect to the database.

Log:

ERROR: Unable to open database: kodi_music60 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music59 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music58 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music57 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music56 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music55 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music54 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music53 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music52 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music51 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music50 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music49 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music48 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music47 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music46 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music45 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.628 T:140317719516928   ERROR: Unable to open database: kodi_music44 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_music43 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_music42 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_music41 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_music40 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_music39 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_music38 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_music37 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_music36 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_music35 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_music34 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_music33 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_music32 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_music60 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to create new database
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_video107 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.629 T:140317719516928   ERROR: Unable to open database: kodi_video106 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.630 T:140317719516928   ERROR: Unable to open database: kodi_video105 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.630 T:140317719516928   ERROR: Unable to open database: kodi_video104 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.630 T:140317719516928   ERROR: Unable to open database: kodi_video103 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.630 T:140317719516928   ERROR: Unable to open database: kodi_video102 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.630 T:140317719516928   ERROR: Unable to open database: kodi_video101 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.630 T:140317719516928   ERROR: Unable to open database: kodi_video100 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.630 T:140317719516928   ERROR: Unable to open database: kodi_video99 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.638 T:140317719516928   ERROR: Unable to open database: kodi_video98 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.638 T:140317719516928   ERROR: Unable to open database: kodi_video97 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.638 T:140317719516928   ERROR: Unable to open database: kodi_video96 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.638 T:140317719516928   ERROR: Unable to open database: kodi_video95 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.638 T:140317719516928   ERROR: Unable to open database: kodi_video94 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video93 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video92 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video91 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video90 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video89 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video88 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video87 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video86 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video85 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video84 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video83 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video82 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video81 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video80 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video79 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.639 T:140317719516928   ERROR: Unable to open database: kodi_video78 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_video77 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_video76 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_video75 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_video107 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to create new database
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_tv29 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_tv28 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_tv27 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_tv26 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_tv25 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_tv24 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_tv23 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_tv22 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_tv21 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_tv20 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_tv19 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.640 T:140317719516928   ERROR: Unable to open database: kodi_tv18 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_tv17 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_tv16 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_tv15 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_tv14 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_tv13 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_tv12 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_tv11 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_tv29 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to create new database
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_epg11 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_epg10 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_epg9 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_epg8 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_epg7 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_epg6 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_epg5 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_epg4 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.641 T:140317719516928   ERROR: Unable to open database: kodi_epg11 [2003](Can't connect to MySQL server on '192.168.70.10' (101))
22:45:26.642 T:140317719516928   ERROR: Unable to create new database

**Comment by solbero** [comment]
In Kodi, go to “Settings” → “System Settings” → “Power saving” and turn “Try to wake remote servers on access” to On.

**Comment by mknuepfer** [comment]
OK, That is working. Thank you
