### ISSUE TITLE
Change keyboard layout

### ISSUE THREAD

**Issue by bishamontn** [solbero/guide-kodi-lutris#3]
First of all, thank you for your guide, it's very easy to follow and so much instructive. 

I have just a problem with my USB keyboard. I choose the right layout (in my case Spanish) in the instalation, then in the xfce desktop for both users (admin and kodi autostartup user) and the layout works great there but in Openbox Kodi Autostart the keyboard is always in English layout and I can't change it. Even if I run kodi from desktop the keyboard works fine so it's not a Kodi configuration problem I guess it's something about the autostart. If you can help me with this I will be grateful.

Thank you so much again for this guide.

**Comment by solbero** [comment]
It is an Openbox problem.

You can set the keyboard layout in Openbox using the terminal command `setxkbmap [layout]`. I’m using a norwegian layout, so for me it would be `setxkbmap no`.

To make Openbox apply this at startup we need to add it to `~/.config/openbox/autostart`. Make sure you are editing the autostart file residing in the home folder of the Kodi user. Open this file using a text editor and append to the end of it.
```
# Set keyboard layout
setxkbmap [layout]
```

You can find more information about the `setxkbmap` command on the [Arch Wiki](https://wiki.archlinux.org/index.php/Keyboard_configuration_in_Xorg#Setting_keyboard_layout).

**Comment by bishamontn** [comment]
Working! Thank you so much. I don't know why but I haven't `~/.config/openbox/` folder I have my file in `/etc/X11/openbox` in case anyone has the same problem maybe this could help.

**Comment by solbero** [comment]
I would not add `setxkbmap` to `/etc/X11/openbox`. That is a system file which could be overwritten when Openbox is updated. Instead create the `openbox` folder and the `autostart` file in `~/.config` and add `setxkbmod` there.
