### ISSUE TITLE
No gui

### ISSUE THREAD

**Issue by lefty420** [solbero/guide-kodi-lutris#4]
Did you guys ever work out a no gui mode?

**Comment by solbero** [comment]
No, sorry. It is a feature of the Lutris client. You can add to this feature request: https://github.com/lutris/lutris/issues/578

**Comment by lefty420** [comment]
Thanks man I'd love a no gui mode it's a pain to have to keep closing it. I'll post on lurtis.

**Comment by solbero** [comment]
The latest version of Lutris and v.1.3.0 of the Kodi Lutris Add-on adds a no-gui mode as default.
