### ISSUE TITLE
slight update for the instructions

### ISSUE THREAD

**Issue by tommyp-vr4** [solbero/guide-kodi-lutris#5]
Hi - I ran thru these instructions to auto launch kodi (sorry I can't figure out lutris but the auto-start works fine).  You should include installation of openbox (unless you intentionally wanted the apt-get -f install to fix the kodi-openbox.deb file).  I also needed to install fakeroot on my debian system.  All aren't showstoppers, just some feedback.  
Thanks for preparing these instructions!
tommyp

**Comment by solbero** [comment]
I'm planning on doing a clean-up and rewrite when Ubuntu 18.04 and Kodi v.18 Leia are released. I'll add your suggestions then.

**Comment by JanStevens** [comment]
Any update on this? v18.04 has landed, I upgraded and now kodi doesn't start anymore :D, could use an updated guide to check my config! Thanks a lot!

**Comment by JanStevens** [comment]
Ha for some reason upgrade to 18.04 uninstalled kodi and kodi-openbox, reinstalled those again and it all worked!

**Comment by solbero** [comment]
Glad you made it work. I'm still waiting for Kodi Leia to be released before I do the rewrite.

**Comment by solbero** [comment]
I have done a revrite of the guide and updated the instructions to Ubuntu 18.04.
