### ISSUE TITLE
Added dailout for cec device permissions in kodi

### ISSUE THREAD

**Issue by lefty420** [solbero/guide-kodi-lutris#6]
Amazing guide I updated from your previous guide from the kodi forum. 
I had issues with my cec device not getting permissions so I added dialout to the user group this fixed it. I'm not great with github but i think i submitted the change.

**Comment by solbero** [comment]
Your PR has been merged in commit https://github.com/solbero/guide-kodi-lutris/commit/eb1c741c76975d8c60b96f6cccde9d6c68cb815f
